# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='Status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
