# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Status',
            new_name='Password',
        ),
    ]
