# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_auto_20190313_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='Email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water',
            name='Phoneno',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
