# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_auto_20190315_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='adminlog',
        ),
    ]
