# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_auto_20190315_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminlog',
        ),
    ]
