# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0007_delete_adminlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water',
            name='Salary',
        ),
    ]
