# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_remove_water_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('Date', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Complaint', models.CharField(max_length=30)),
            ],
        ),
    ]
