# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0009_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
