# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-01 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(max_length=30)),
                ('reply', models.CharField(max_length=30)),
            ],
        ),
    ]
