# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-01 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_complaintreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaintreply',
        ),
    ]
