# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('Date', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Complaint', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=30)),
                ('Pincode', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Aadhar', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Confirm_Password', models.CharField(max_length=30)),
            ],
        ),
    ]
