# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Complaint',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Date',
            new_name='Compalint',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Subject',
            new_name='Compalint_description',
        ),
        migrations.AddField(
            model_name='complaint',
            name='Pincode',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
