# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190326_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Compalint',
            new_name='Compalaint_description',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Compalint_description',
            new_name='Complaint',
        ),
    ]
