# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20190326_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Compalaint_description',
            new_name='Complaint_description',
        ),
    ]
