# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190326_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='Complan',
        ),
    ]
