# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20190329_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complan',
            name='uid',
            field=models.CharField(max_length=30),
        ),
    ]
