# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20190329_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='iid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='User.Complan'),
            preserve_default=False,
        ),
    ]
