# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_userreg_iid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='iid',
        ),
        migrations.AlterField(
            model_name='complan',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userreg'),
        ),
    ]
