# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_complan_complaint_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complan',
            name='Complaint_Reply',
            field=models.CharField(default='', max_length=30),
        ),
    ]
